version: '3.8'

services:
  gitea-openai-review-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gitea-review-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - REVIEW_BOT_SERVER_PORT=8080
      - REVIEW_BOT_GITEA_URL=${GITEA_URL}
      - REVIEW_BOT_GITEA_BOT_TOKEN=${GITEA_BOT_TOKEN}
      - REVIEW_BOT_GITEA_WEBHOOK_SECRET=${GITEA_WEBHOOK_SECRET}
      - REVIEW_BOT_OPENAI_API_KEY=${OPENAI_API_KEY}
      - REVIEW_BOT_OPENAI_MODEL=gpt-4
    volumes:
      - ../configs:/app/configs:ro
      - ./logs:/app/logs
    networks:
      - review-bot-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: review-bot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - review-bot-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  redis-data:
    driver: local

networks:
  review-bot-network:
    driver: bridge